pipeline:
  create-db:
    db1:
      action: dsunit:init
      datastore: db1
      config:
        driverName: bigquery
        credentials: $bqCredentials
        parameters:
          datasetId: db1
      recreate: true
      scripts:
      - URL: datastore/db1/schema.sql
    db2:
      action: dsunit:init
      datastore: db2
      recreate: true
      config:
        driverName: mysql
        descriptor: '[username]:[password]@tcp(127.0.0.1:3306)/[dbname]?parseTime=true'
        credentials: $mysqlCredentials
      admin:
        datastore: mysql
        config:
          driverName: mysql
          descriptor: '[username]:[password]@tcp(127.0.0.1:3306)/[dbname]?parseTime=true'
          credentials: $mysqlCredentials
      scripts:
      - URL: datastore/db2/schema.sql
  prepare:
    db1:
      action: dsunit:prepare
      datastore: db1
      URL: datastore/db1/data
    db2:
      action: dsunit:prepare
      datastore: db2
      URL: datastore/db2/data
