init:
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  serviceTarget: $target
  targetHost: $Hostname($target.URL)
  appVersion: 0.1
  bqCredentials: bq-am
  mysqlCredentials: mysql
defaults:
  target: $target
  bqCredentials: $bqCredentials
  mysqlCredentials: $mysqlCredentials
pipeline:
  init:
     system:
          action: run
          request: '@system'
          tasks: '*'
     datastore:
          action: run
          request: '@datastore'
          tasks: '*'
